# Bulk API Trigger Configuration
# ================================

# Watchdog settings for file monitoring
watchdog:
  enabled: true
  watch_paths:
    - /app/data/csv
  auto_process: true
  processing_workers: 1           # Add: file worker threads (env can override)
  debounce_delay: 3.0
  max_queue_size: 100


# Rate limiting and performance settings
rate_limiting:
  base_rate_limit: 2.0        # Minimum delay between requests (seconds)
  starting_rate_limit: 2.0    # Initial delay
  max_rate_limit: 10.0        # Maximum delay when errors occur
  window_size: 20             # Number of requests to analyze for rate adjustment
  error_threshold: 0.3        # Error rate threshold (30%)
  max_workers: 5              # Maximum parallel requests

# Retry and timeout settings
retry:
  max_retries: 3              # Number of retries per failed request
  retry_delay: 1.0            # Base delay between retries (seconds) - now properly used
  timeout: 30                 # Request timeout (seconds)

# Deployment settings
deployment:
  keep_alive: true            # Keep container running after completion
  skip_rows: 0                # Number of rows to skip in CSV
  job_name: null              # Custom job name (null = auto-generate)
  metrics_enabled: true       # Enable system metrics collection
  health_check_enabled: true  # Enable health check endpoint
  report_path: /app/data/reports  # Path for job reports
  report_keep: 200                # Add: max JSON reports to retain

# Notification settings
notifications:
  email:
    enabled: false
    smtp_server: smtp.gmail.com
    smtp_port: 587
    username: your_email@gmail.com
    password: your_app_password  # Use app password for Gmail
    from_email: your_email@gmail.com
    recipients:
      - admin@example.com
      - team@example.com
    notify_on_completion: true
    notify_on_file_detected: false
  slack:
    enabled: false
    webhook_url: https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
    notify_on_completion: true
    notify_on_file_detected: true
    notify_on_progress: false         # Add: enable progress messages
    progress_every_n: 25              # Add: send progress every N items
    progress_urgency: auto            # Add: auto/low/normal/high/critical
    progress_first_at_n: 10           # Add: first progress only after N processed
    progress_min_pct: 5               # Add: minimum % threshold before sending


# Database settings
database:
  enabled: true
  path: /app/data/webhook_results.db
  backup_enabled: true
  backup_interval_hours: 24

# CSV processing settings
csv:
  chunk_size: 1000
  required_columns: ["webhook_url"]                      # Add
  optional_columns: ["method","payload","header","name","group"]  # Add
  archive_processed: true
  archive_path: /app/data/csv/processed
  duplicates_path: /app/data/csv/duplicates
  rejected_path: /app/data/csv/rejected
  archive_on_validation_failure: true
  file_patterns:
    - "/app/data/csv/*.csv"
    - "/app/data/*.csv"