version: '3.8'

services:
  bulk-api-trigger:
    build: .
    container_name: bulk-api-trigger
    restart: unless-stopped
    ports:
      - "8000:8000"  # Expose health check port
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
    environment:
      # Deployment Settings
      - DEPLOYMENT_MODE=true
      - KEEP_ALIVE=true
      - JOB_NAME=Docker Bulk API Job
      - WATCHDOG_ENABLED=true
      - WATCH_PATHS=/app/data/csv
      - REPORT_PATH=/app/data/reports
      
      # CSV Processing
      - CSV_FILE=AUTO
      - DEBOUNCE_DELAY=3.0
      - SKIP_ROWS=0
      - ARCHIVE_PROCESSED=true
      - ARCHIVE_PATH=/app/data/csv/processed
      - DUPLICATES_PATH=/app/data/csv/duplicates
      - REJECTED_PATH=/app/data/csv/rejected
      
      # Rate Limiting
      - MAX_WORKERS=5
      - BASE_RATE_LIMIT=2.0
      - STARTING_RATE_LIMIT=2.0
      - MAX_RATE_LIMIT=10.0
      - ERROR_THRESHOLD=0.3
      - WINDOW_SIZE=20
      - PROCESSING_WORKERS=5
      - GLOBAL_MAX_REQUESTS=20
      
      # Request Settings
      - MAX_RETRIES=3
      - REQUEST_TIMEOUT=30
      - RETRY_DELAY=1.0
      
      # Database
      - DATABASE_ENABLED=true
      - DATABASE_PATH=/app/data/webhook_results.db
      - DATABASE_BACKUP_ENABLED=true
      - DATABASE_BACKUP_INTERVAL_HOURS=24
      
      # Health & Metrics
      - HEALTH_CHECK_ENABLED=true
      - HEALTH_PORT=8000
      - METRICS_ENABLED=true
      
      # Logging
      - LOG_LEVEL=INFO
      - MAX_LOG_SIZE_MB=100
      
      # Notifications (uncomment and configure as needed)
      # - EMAIL_NOTIFICATIONS=true
      # - EMAIL_SMTP_SERVER=smtp.gmail.com
      # - EMAIL_SMTP_PORT=587
      # - EMAIL_USERNAME=your_email@gmail.com
      # - EMAIL_PASSWORD=your_app_password
      # - EMAIL_FROM=your_email@gmail.com
      # - EMAIL_RECIPIENTS=admin@example.com,team@example.com
      
      # - SLACK_NOTIFICATIONS=true
      # - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
      # - SLACK_NOTIFY_PROGRESS=true
      
    # Enhanced health check
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:8000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Web dashboard for monitoring (future enhancement)
  # dashboard:
  #   image: nginx:alpine
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./dashboard:/usr/share/nginx/html:ro
  #   depends_on:
  #     - bulk-api-trigger

volumes:
  bulk_api_data:
    driver: local